services:
  wbgt:
    image: caddy:alpine
    container_name: wbgt
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/usr/share/caddy:ro
      - caddy_data:/data

volumes:
  caddy_data:
